const app = document.querySelector('#app');
const state = { classes: [], selectedClassId: null, publicPage: 'timetable', adminPage: 'dashboard', edit: null };
const ADMIN_PAGES = ['dashboard', 'timetables', 'assignments', 'announcements', 'enquiries'];
let adminNavigationBound = false;
const $ = (selector, root = document) => root.querySelector(selector);
const esc = (v = '') => String(v).replace(/[&<>'"]/g, ch => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[ch]));
const dateText = value => new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value.slice(0,10)}T00:00:00`));
const shortDate = value => new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(new Date(value));
const icon = value => esc(value || '✦');

async function api(url, options = {}) {
  const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'Something went wrong.');
  return body;
}
function notify(target, text, bad = false) { const previous = $('.message', target); if (previous) previous.remove(); const el=document.createElement('div'); el.className=`message${bad?' error':''}`;el.textContent=text;target.prepend(el); }
function tabs(active) { return `<nav class="tabs" aria-label="Portal navigation">${[['timetable','Timetable'],['announcements','Announcements'],['assignments','Assignments'],['enquiry','Enquiry']].map(([key,label])=>`<a href="#${key}" class="${key===active?'active':''}">${label}</a>`).join('')}</nav>`; }
function intro(title, text) { return `<section class="page-intro"><div class="eyebrow">The Learning Steps Pre School</div><h1>${title}</h1><p>${text}</p></section>`; }
function picker() { return `<section class="card class-picker"><span class="section-label">Select Class</span><div class="chips">${state.classes.map(c=>`<button class="chip ${c.id===state.selectedClassId?'active':''}" data-class="${c.id}">${esc(c.name)}</button>`).join('')}</div></section>`; }
function bindPicker(render) { document.querySelectorAll('[data-class]').forEach(button => button.addEventListener('click', () => { state.selectedClassId=Number(button.dataset.class); render(); })); }
async function loadClasses() { state.classes = await api('/api/public/classes'); if (!state.selectedClassId) state.selectedClassId=state.classes[0]?.id; }
function publicShell(page, content) { app.innerHTML=`${intro({timetable:'Your child’s day, beautifully planned',announcements:'School news & reminders',assignments:'Classroom learning at home',enquiry:'We’re here to help'}[page],{timetable:'Choose a class to view its week-at-a-glance timetable.',announcements:'The latest updates from The Learning Steps.',assignments:'Choose a class to see only its current learning activities.',enquiry:'Send us a message and our school team will get back to you.'}[page])}${tabs(page)}${content}`; }
async function renderTimetable() { publicShell('timetable', `${picker()}<div id="results" class="empty">Loading timetable…</div>`); bindPicker(renderTimetable); try { const rows=await api(`/api/public/timetable?classId=${state.selectedClassId}`); const byDay=Object.groupBy(rows,row=>row.day); $('#results').outerHTML=rows.length?`<div id="results">${['Monday','Tuesday','Wednesday','Thursday','Friday'].map(day=>`<section><h2 class="day-heading">${day}</h2><div class="timeline">${(byDay[day]||[]).map(row=>`<article class="card entry" style="--dot:var(--${esc(row.category)})"><div class="entry-icon">${icon(row.icon)}</div><div><h3><time>${esc(row.time)}</time>${esc(row.activity)}</h3>${row.description?`<p>${esc(row.description)}</p>`:''}</div></article>`).join('')||'<p class="empty">No activities added yet.</p>'}</div></section>`).join('')}</div>`:`<div id="results" class="empty">No timetable entries have been added for this class yet.</div>`; } catch(e) { $('#results').textContent=e.message; } }
async function renderAssignments() { publicShell('assignments', `${picker()}<div id="results" class="empty">Loading assignments…</div>`); bindPicker(renderAssignments); try { const rows=await api(`/api/public/assignments?classId=${state.selectedClassId}`); $('#results').outerHTML=rows.length?`<div id="results" class="assignment-grid">${rows.map(row=>`<article class="card assignment"><div class="subject">${esc(row.subject)}${row.important?'<span class="badge">IMPORTANT</span>':''}</div><h3>${esc(row.title)}</h3><p>${esc(row.instructions)}</p><div class="due"><span>Assigned: ${dateText(row.assigned_date)}</span><strong>Due: ${dateText(row.due_date)}</strong></div></article>`).join('')}</div>`:`<div id="results" class="empty">No assignments have been added for this class yet.</div>`; }catch(e){$('#results').textContent=e.message;} }
async function renderAnnouncements() { publicShell('announcements','<div id="results" class="announcement-grid"><div class="empty">Loading announcements…</div></div>'); try{const rows=await api('/api/public/announcements');$('#results').innerHTML=rows.length?rows.map(row=>`<article class="card notice ${row.important?'important':''}"><h3>${esc(row.title)}${row.important?'<span class="badge">IMPORTANT</span>':''}</h3><p>${esc(row.content)}</p><div class="meta">Posted ${shortDate(row.posted_at)}</div></article>`).join(''):'<div class="empty">No announcements have been posted yet.</div>';}catch(e){$('#results').textContent=e.message;} }
function renderEnquiry() { publicShell('enquiry',`<form id="enquiry-form" class="card form-card" novalidate><div class="field"><label for="parentName">Parent/Guardian name</label><input id="parentName" name="parentName" required maxlength="120" autocomplete="name"></div><div class="form-row"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required maxlength="160" autocomplete="email"></div><div class="field"><label for="phone">Phone number</label><input id="phone" name="phone" inputmode="tel" required maxlength="30" autocomplete="tel"></div></div><div class="field"><label for="message">Message</label><textarea id="message" name="message" required minlength="10" maxlength="2000"></textarea></div><button class="button primary" type="submit">Send enquiry</button></form>`);$('#enquiry-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const r=await api('/api/public/enquiries',{method:'POST',body:JSON.stringify(data)});form.reset();notify(form,r.message);}catch(err){notify(form,err.message,true);}}); }
function renderPublic() { const page=(location.hash||'#timetable').slice(1); state.publicPage=['timetable','announcements','assignments','enquiry'].includes(page)?page:'timetable'; if(state.publicPage==='timetable')return renderTimetable();if(state.publicPage==='assignments')return renderAssignments();if(state.publicPage==='announcements')return renderAnnouncements();renderEnquiry(); }

function brandMarkup() { return '<a class="brand" href="/" aria-label="The Learning Steps Pre School home"><img src="/assets/tls-logo.png" alt="The Learning Steps logo"><span><strong>THE LEARNING STEPS</strong><small>Pre School Portal</small></span></a>'; }
function adminPageFromHash() { const page=location.hash.slice(1); return ADMIN_PAGES.includes(page)?page:'dashboard'; }
function adminHref(page) { return page==='dashboard'?'/admin':`/admin#${page}`; }
function adminNav(active) { return `<nav class="admin-nav" aria-label="Admin navigation">${[['dashboard','Dashboard'],['timetables','Timetable'],['assignments','Assignments'],['announcements','Announcements'],['enquiries','Enquiries']].map(([key,label])=>`<a href="${adminHref(key)}" data-admin-page="${key}" class="${key===active?'active':''}">${label}</a>`).join('')}<button id="logout" type="button" class="button small">Logout</button></nav>`; }
function navigateAdmin(event) { event.preventDefault(); const page=event.currentTarget.dataset.adminPage; const target=adminHref(page); if(`${location.pathname}${location.hash}`!==target) history.pushState({adminPage:page},'',target); state.edit=null; renderAdmin(); }
function adminShell(content) { app.innerHTML=`<div class="admin-shell"><header class="admin-head"><div class="admin-brand-group">${brandMarkup()}<span class="admin-area-label">Admin area</span></div><a class="admin-link" href="/">View public portal</a></header>${adminNav(state.adminPage)}<section class="admin-content">${content}</section></div>`;document.querySelectorAll('[data-admin-page]').forEach(link=>link.addEventListener('click',navigateAdmin));$('#logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.href='/admin';}); }
function options(selected) { return state.classes.map(c=>`<option value="${c.id}" ${c.id===Number(selected)?'selected':''}>${esc(c.name)}</option>`).join(''); }
function checkbox(name, checked, label) { return `<label class="check"><input type="checkbox" name="${name}" ${checked?'checked':''}> ${label}</label>`; }
function rowActions(kind, item) { return `<div class="row-actions"><button class="button small" data-edit="${kind}" data-id="${item.id}">Edit</button><button class="button danger small" data-delete="${kind}" data-id="${item.id}">Delete</button></div>`; }
async function renderDashboard() { adminShell('<div id="admin-result" class="empty">Loading dashboard…</div>');try{const d=await api('/api/admin/dashboard');$('#admin-result').outerHTML=`<div id="admin-result"><div class="admin-section-title"><div><h2>Welcome back</h2><p>Manage family-facing information from one simple place.</p></div></div><div class="stats">${[['Classes',d.classes],['Timetable entries',d.timetable],['Assignments',d.assignments],['Announcements',d.announcements],['Unread enquiries',d.unreadEnquiries]].map(([l,v])=>`<article class="card stat"><span class="meta">${l}</span><strong>${v}</strong></article>`).join('')}</div><article class="card" style="margin-top:16px"><h3 style="margin-top:0">Demo data is ready</h3><p class="mobile-note">The initial records are labelled DEMO DATA in their content. You can edit or remove them as the school’s real timetable and notices become available.</p></article><button id="change-password" class="button ghost" style="margin-top:12px">Change password</button><form id="password-form" class="card hidden" style="margin-top:12px"><div class="field"><label>Current password</label><input name="currentPassword" type="password" required autocomplete="current-password"></div><div class="field"><label>New password</label><input name="newPassword" type="password" required minlength="12" maxlength="256" autocomplete="new-password"></div><button class="button primary" type="submit">Update password</button></form></div>`;$('#change-password').addEventListener('click',()=>$('#password-form').classList.remove('hidden'));$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;try{const r=await api('/api/admin/change-password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();notify(form,r.message);}catch(err){notify(form,err.message,true);}});}catch(e){$('#admin-result').textContent=e.message;} }
function timetableForm(item={}) { item=item||{}; return `<form id="manage-form" class="card form-card"><div class="form-row"><div class="field"><label>Class</label><select name="classId">${options(item.class_id||item.classId||state.selectedClassId)}</select></div><div class="field"><label>Day</label><select name="day">${['Monday','Tuesday','Wednesday','Thursday','Friday'].map(day=>`<option ${day===(item.day||'Monday')?'selected':''}>${day}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label>Time</label><input name="time" type="time" required value="${esc(item.time||'09:00')}"></div><div class="field"><label>Title / activity</label><input name="activity" required maxlength="100" value="${esc(item.activity||'')}"></div></div><div class="form-row"><div class="field"><label>Icon (optional)</label><input name="icon" maxlength="8" value="${esc(item.icon||'')}" placeholder="e.g. Aa"></div><div class="field"><label>Colour</label><select name="category">${['blue','yellow','mint','coral','purple','pink'].map(c=>`<option value="${c}" ${c===(item.category||'blue')?'selected':''}>${c[0].toUpperCase()+c.slice(1)}</option>`).join('')}</select></div></div><div class="field"><label>Description (optional)</label><textarea name="description" maxlength="500">${esc(item.description||'')}</textarea></div><button class="button primary" type="submit">${state.edit?'Save changes':'Add timetable entry'}</button> ${state.edit?'<button class="button ghost" type="button" id="cancel-edit">Cancel</button>':''}</form>`; }
function assignmentForm(item={}) { item=item||{}; return `<form id="manage-form" class="card form-card"><div class="form-row"><div class="field"><label>Class</label><select name="classId">${options(item.class_id||item.classId||state.selectedClassId)}</select></div><div class="field"><label>Subject</label><input name="subject" required maxlength="80" value="${esc(item.subject||'')}"></div></div><div class="field"><label>Assignment title</label><input name="title" required maxlength="140" value="${esc(item.title||'')}"></div><div class="field"><label>Instructions</label><textarea name="instructions" required minlength="5" maxlength="2000">${esc(item.instructions||'')}</textarea></div><div class="form-row"><div class="field"><label>Assigned date</label><input name="assignedDate" type="date" required value="${esc(item.assigned_date||'')}"></div><div class="field"><label>Due date</label><input name="dueDate" type="date" required value="${esc(item.due_date||'')}"></div></div>${checkbox('important',item.important,'Mark as important')}<br><button class="button primary" type="submit">${state.edit?'Save changes':'Add assignment'}</button> ${state.edit?'<button class="button ghost" type="button" id="cancel-edit">Cancel</button>':''}</form>`; }
function announcementForm(item={}) { item=item||{}; return `<form id="manage-form" class="card form-card"><div class="field"><label>Announcement title</label><input name="title" required maxlength="160" value="${esc(item.title||'')}"></div><div class="field"><label>Announcement content</label><textarea name="content" required minlength="5" maxlength="3000">${esc(item.content||'')}</textarea></div>${checkbox('important',item.important,'Mark as important')}<br><button class="button primary" type="submit">${state.edit?'Save changes':'Post announcement'}</button> ${state.edit?'<button class="button ghost" type="button" id="cancel-edit">Cancel</button>':''}</form>`; }
async function renderManagement(kind) { const singular={timetables:'timetable entry',assignments:'assignment',announcements:'announcement'}[kind]; adminShell(`<div class="admin-section-title"><div><h2>${singular[0].toUpperCase()+singular.slice(1)} management</h2><p>Create, edit, or delete items. Updates immediately appear on the public portal.</p></div></div>${kind==='timetables'?timetableForm(state.edit):kind==='assignments'?assignmentForm(state.edit):announcementForm(state.edit)}<div id="list" class="admin-list"><div class="empty">Loading…</div></div>`);bindManageForm(kind);try{const rows=await api(`/api/admin/${kind}`);renderAdminList(kind,rows);}catch(e){$('#list').textContent=e.message;} }
function renderAdminList(kind, rows) { const list=$('#list'); if(!rows.length){list.innerHTML='<div class="empty">Nothing has been added yet.</div>';return;}list.innerHTML=rows.map(row=>{let title,details;if(kind==='timetables'){title=`${esc(row.class_name)} · ${esc(row.day)} · ${esc(row.time)} — ${esc(row.activity)}`;details=esc(row.description||'No description');}else if(kind==='assignments'){title=`${esc(row.class_name)} · ${esc(row.subject)} — ${esc(row.title)}`;details=`Due ${dateText(row.due_date)}${row.important?' · Important':''}`;}else{title=esc(row.title);details=`${esc(row.content.slice(0,180))}${row.content.length>180?'…':''}`;}return `<article class="card admin-row"><div><h3>${title}</h3><p>${details}</p></div>${rowActions(kind,row)}</article>`}).join('');bindRowActions(kind,rows); }
function bindManageForm(kind) { const form=$('#manage-form');form.addEventListener('submit',async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));values.important=$('[name="important"]',form)?.checked||false;try{const url=state.edit?`/api/admin/${kind}/${state.edit.id}`:`/api/admin/${kind}`;await api(url,{method:state.edit?'PATCH':'POST',body:JSON.stringify(values)});state.edit=null;renderAdmin();}catch(err){notify(form,err.message,true);}});$('#cancel-edit')?.addEventListener('click',()=>{state.edit=null;renderAdmin();}); }
function bindRowActions(kind, rows) { document.querySelectorAll(`[data-edit="${kind}"]`).forEach(button=>button.addEventListener('click',()=>{state.edit=rows.find(r=>r.id===Number(button.dataset.id));renderAdmin();}));document.querySelectorAll(`[data-delete="${kind}"]`).forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Delete this item? This cannot be undone.'))return;try{await api(`/api/admin/${kind}/${button.dataset.id}`,{method:'DELETE'});renderAdmin();}catch(e){alert(e.message);}})); }
async function renderEnquiries() { adminShell('<div class="admin-section-title"><div><h2>Enquiries</h2><p>Private messages submitted by parents and visitors.</p></div></div><div id="list" class="admin-list"><div class="empty">Loading…</div></div>');try{const rows=await api('/api/admin/enquiries');const list=$('#list');list.innerHTML=rows.length?rows.map(row=>`<article class="card admin-row"><div><h3>${esc(row.parent_name)} ${row.is_read?'':'<span class="badge">NEW</span>'}</h3><p>${esc(row.message)}</p><div class="meta">${esc(row.email)} · ${esc(row.phone)} · ${shortDate(row.created_at)}</div></div><div class="row-actions"><button class="button small" data-read="${row.id}" data-value="${!row.is_read}">${row.is_read?'Mark unread':'Mark read'}</button><button class="button danger small" data-enquiry-delete="${row.id}">Delete</button></div></article>`).join(''):'<div class="empty">No enquiries yet.</div>';document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',async()=>{await api(`/api/admin/enquiries/${b.dataset.read}`,{method:'PATCH',body:JSON.stringify({isRead:b.dataset.value==='true'})});renderEnquiries();}));document.querySelectorAll('[data-enquiry-delete]').forEach(b=>b.addEventListener('click',async()=>{if(confirm('Delete this enquiry?')){await api(`/api/admin/enquiries/${b.dataset.enquiryDelete}`,{method:'DELETE'});renderEnquiries();}}));}catch(e){$('#list').textContent=e.message;} }
async function renderAdmin() { state.adminPage=adminPageFromHash(); state.edit=null; if(state.adminPage==='dashboard')return renderDashboard();if(state.adminPage==='enquiries')return renderEnquiries();return renderManagement(state.adminPage); }
function bindAdminNavigation() { if (!adminNavigationBound) { const rerenderFromLocation=()=>renderAdmin(); window.addEventListener('hashchange',rerenderFromLocation); window.addEventListener('popstate',rerenderFromLocation); adminNavigationBound=true; } }
async function startAdminApp() { await loadClasses(); bindAdminNavigation(); await renderAdmin(); }
function renderLogin() { app.innerHTML=`<section class="admin-auth card">${brandMarkup()}<div class="eyebrow" style="margin-top:18px">Secure access</div><h1>Admin sign in</h1><p>Use the local administrator account configured for this portal.</p><form id="login-form"><div class="field"><label>Email</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" required autocomplete="current-password"></div><button class="button primary" type="submit">Sign in</button></form></section>`;$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;try{await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await startAdminApp();}catch(err){notify(form,err.message,true);}}); }
async function init() { if(location.pathname==='/admin'){document.body.classList.add('admin-page');try{await api('/api/admin/me');await startAdminApp();}catch{renderLogin();}return;}await loadClasses();renderPublic();window.addEventListener('hashchange',renderPublic); }
init().catch(e=>{app.innerHTML=`<div class="card empty">Unable to load the portal: ${esc(e.message)}</div>`;});
